use strict;
use warnings;

my %targets = (
    "wasix32" => {
        inherit_from => [ "BASE_unix" ],
        CC => "clang",
        CXX => "clang++",
        CFLAGS => picker(default => "-Wall",
                         debug => "-O0 -g",
                         release => "-O2"),
        CXXFLAGS => picker(default => "-Wall",
                          debug => "-O0 -g",
                          release => "-O2"),
        cflags => add("--target=wasm32-wasi"),
        cxxflags => add("--target=wasm32-wasi -std=c++11"),
        lib_cppflags => add("-DL_ENDIAN -DOPENSSL_NO_SECURE_MEMORY -DOPENSSL_USE_NODELETE -D_WASI_EMULATED_PROCESS_CLOCKS"),
        ex_libs => add("-lwasi-emulated-process-clocks"),
        bn_ops => "BN_LLONG",
        thread_scheme => "none",
        perlasm_scheme => "void",
    },
);
